version: '3.7'

services:
  frontend_app:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
      target: app
    command: yarn start
    restart: on-failure
    volumes:
      - './:/app'
    ports:
      - '3005:3000'
    env_file:
      - .env
